### ISSUE TITLE
GA4 AMP data about 60% lower than GA UA data

### ISSUE THREAD

**Issue by pabloaugusto** [analytics-debugger/google-analytics-4-for-amp#21] opened 2023-05-02 12:47 UTC
Hello.

The conversation started at this thread

- https://github.com/ampproject/amphtml/issues/24621#issuecomment-1484175041
-  https://github.com/ampproject/amphtml/issues/24621#issuecomment-1517494658 

was moved here, since it's a non official amp project investigation thread.

----------------

I have the same problem (GA4 AMP data LOWER than GA UA AMP data) here. 
My data is about 60% smaller in GA4 AMP.

I'm hosting the ga4.file myself too. 

EXAMPLE
======
GA UA AMP pageviews on 23/04: 422.765
GA4 AMP pageviews on 23/04: 162.489 (61,6% lower)

How we can see, is a huge difference.

**Comment by thyngster** [comment] 2023-05-02 12:50
@pabloaugusto as I already mentioned, you need to have in mind that if you're selfhosting the file, some people will come from Google/AMP CDN, and either you send back the CORS headers accordingly or those visits won't be tracked. Some users on the thread have confirmed of going to a ~2% difference after fixing their setup.

**Comment by thyngster** [comment] 2023-05-02 12:52
YOu need to make your server to add the following headers to the ga4.json files requests:

Access-Control-Allow-Origin: {$origin}
Access-Control-Allow-Credentials: true

Being origin the current request http origin.

**Comment by pabloaugusto** [comment] 2023-05-02 13:01
Thanks in advance @thyngster.
I did some debug here and confirmed CORS problem here at site.

Will fix it and give a feedback

**Comment by fanatixgithub** [comment] 2023-05-02 13:08
> Some users on the thread have confirmed of going to a ~2% difference after fixing their setup.

Yep, this was me. Thanks to David's advice, adding the CORS headers fixed everything. It's all been within a couple percentage points since adding this.

In case you're adding the headers directly in nginx, you can reference a var $http_origin, like so:

```
location = /ga4.json {
    add_header Access-Control-Allow-Origin $http_origin;
    add_header Access-Control-Allow-Credentials true;
#    proxy_pass or try_files or whatever might need to go here
}
```

**Comment by thyngster** [comment] 2023-05-02 14:07
At my end I'm pushing a code update this week to add some new support to some things, and I'll add a section on the docs about this, so it's crear for everyone.

**Comment by thyngster** [comment] 2023-05-02 17:38
ok, new features and improved documentation about CORS in now merged. Thanks for your time!

**Comment by pabloaugusto** [comment] 2023-05-04 12:34
> 

It works @thyngster 
You can close the issue now.

Thanks!

**Comment by thyngster** [comment] 2023-05-04 18:48
Great to hear that it's now working! Thank you for the report, and I apologize for not writing a more proper documentation about this from the start.

**Closed as completed by thyngster** 2023-05-04 18:48 UTC
